name: Publish

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

jobs:
  maven:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v5
        with:
          submodules: recursive
      - uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 17
      - uses: android-actions/setup-android@v4
        with:
          packages: platform-tools
      - uses: gradle/actions/setup-gradle@v5
      - name: Publish to GitHub Packages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./gradlew publish --no-daemon
